language: objective-c

env:
  global:
    - PLATFORM=macosx
    - LUAROCKS_VER=2.1.0

  matrix:
    - LUA=lua5.1 LUA_SFX=
    - LUA=lua5.2 LUA_SFX=
    - LUA=luajit LUA_SFX=jit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh

install:
  - sudo luarocks install lzmq-timer
  - sudo luarocks install lunitx
  - sudo luarocks make rockspecs/luq-scm-0.rockspec

script:
  - cd test
  - lunit.sh -i lua$LUA_SFX test_pool.lua

notifications:
  email:
    on_success: change
    on_failure: always