language: objective-c

env:
  global:
    - LUAROCKS_VER=2.2.0

  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh

install:
  - sudo luarocks install lzmq-timer
  - sudo luarocks install lunitx
  - sudo luarocks make rockspecs/luq-scm-0.rockspec

script:
  - cd test
  - lunit.sh test_pool.lua

notifications:
  email:
    on_success: change
    on_failure: always